version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rspec
    versions:
    - 3.10.0
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.8.1
    - 1.9.1
